version: "3"
services:
    cms-main-db:
      image: postgres
      container_name: cms_main_db
      restart: always
      volumes:
        - ./data/main_db/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=cms_main_server
        - POSTGRES_USER=main
        - POSTGRES_PASSWORD=20121208
      ports:
        - "5432:5432"

    cms-main:
        image: snslabdocker/cms_main
        container_name: cms_main
        depends_on:
          - cms-main-db
        restart: always
        ports:
          - "8000:8000"
          - "9022:9021"
          - "9999:9999"
        environment:
          - HOST_IP=203.250.32.193
          - DATABASE_IP=cms-main-db
        volumes:
          - ./data/main:/root/LivingLab-CCS/Livinglab_CMS/Livinglab/Livinglab-CMS/cms_main_server/media
        command: sh -c "/bin/bash /root/LivingLab-CCS/Livinglab_CMS/Livinglab/Livinglab-CMS/cms_main_server/start_cms.sh"
        #command: /bin/bash -c "while true; do echo test; sleep 100; done"

    cms-shelter-db:
      image: postgres
      container_name: cms_shelter_db
      restart: always
      command: -p 5433
      volumes:
        - ./data/shelter_db/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=cms_shelter_server
        - POSTGRES_USER=shelter
        - POSTGRES_PASSWORD=20121208
      ports:
        - "5433:5433"

    cms-shelter:
        image: snslabdocker/cms_shelter:0.7
        #image: snslabserver/cms_shelter
        container_name: cms_shelter
        depends_on:
          - cms-shelter-db
        restart: always
        ports:
          - "8001:8000"
          - "3000:3000"
          - "5000:5000"
          - "9021:9021"
          - "9998:9999"
        environment:
          - CMS_MAIN_IP=203.250.32.193
          - DATABASE_IP=cms-shelter-db
        links:
          - cms-shelter-db
        #command: sh -c "/bin/bash /root/LivingLab-CMS-IDLE/Client/client_react/start_idle.sh"
        #command:
        #  - sh /root/LivingLab-CMS-IDLE/Client/client_react/start_idle.sh

        volumes:
          - ./data/shelter:/root/LivingLab-CMS-IDLE/Client/client_react/public/ftp

        #command:
        #  - sh /root/LivingLab-CMS-IDLE/start_shelter.sh
        #  - ./start_shelter.sh
        #command: /bin/bash -c "while true; do echo test; sleep 100; done"