version: "3"
services:
    cms-shelter-db:
      image: postgres
      container_name: cms_shelter_db
      restart: always
      command: -p 5433
      volumes:
        - ./data/shelter_db/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=cms_shelter_server
        - POSTGRES_USER=shelter
        - POSTGRES_PASSWORD=20121208
      ports:
        - "5433:5433"

    cms-shelter:
        image: snslabdocker/cms_shelter:4.3
        #image: snslabserver/cms_shelter
        container_name: cms_shelter
        depends_on:
          - cms-shelter-db
        restart: always
        ports:
          - "8000:8000"
          - "3000:3000"
          - "3001:3001"
          - "5000:5000"
          # - "7000:7000"
          - "9021:9021"
          # - "9999:9999"
        environment:
          - CMS_MAIN_IP=203.250.35.98 # 메인 PC IP 주소
          - CMS_SHELTER_IP=203.250.32.193 # 쉘터 PC IP 주소
          - DATABASE_IP=cms-shelter-db
          - SHELTER_ID=1 # 쉘터 id
          - SHELTER_NAME="DCU" # 쉘터명
          - SHELTER_AUTH_NUMBER="4648569" # 쉘터 인증번호
          - DISPLAY=$DISPLAY
        links:
          - cms-shelter-db
        #command: sh -c "/bin/bash /root/LivingLab-CMS-IDLE/Client/client_react/start_idle.sh"
        #command: sh -c "/bin/bash while true; sleep 7200s;"
        #command:
        #  - /bin/bash start_shelter.sh

        volumes:
          - /tmp/.X11-unix:/tmp/.X11-unix
          - ./data/shelter:/root/LL_Shelter_Sinage/Client/client_react/public/ftp
          #
          # - ./data/shelter/django:/root/LL_Shelter_API-Server