version: "3"
services:
    cms-shelter-db:
      image: postgres
      container_name: cms_shelter_db
      restart: always
      command: -p 5433
      volumes:
        - ./data/shelter_db/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=cms_shelter_server
        - POSTGRES_USER=shelter
        - POSTGRES_PASSWORD=20121208
      ports:
        - "5433:5433"

    cms-shelter:
        image: snslabdocker/cms_shelter:1.5
        #image: snslabserver/cms_shelter
        container_name: cms_shelter
        depends_on:
          - cms-shelter-db
        restart: always
        ports:
          - "8000:8000"
          - "3000:3000"
          - "5000:5000"
          - "9021:9021"
          - "9999:9999"
        environment:
          - CMS_MAIN_IP=203.250.32.193 # 메인 PC IP 주소
          - CMS_SHELTER_IP=203.250.32.193 # 쉘터의 IP 주소
          - DATABASE_IP=cms-shelter-db
        links:
          - cms-shelter-db
        #command: sh -c "/bin/bash /root/LivingLab-CMS-IDLE/Client/client_react/start_idle.sh"
        #command:
        #  - sh /root/LivingLab-CMS-IDLE/Client/client_react/start_idle.sh

        volumes:
          - ./data/shelter:/root/LivingLab-CMS-IDLE/Client/client_react/public/ftp