version: "3"
services:
    cms-shelter-db:
      image: postgres
      container_name: cms_shelter_db
      restart: always
      command: -p 5433
      volumes:
        - ./data/shelter/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=cms_shelter_server
        - POSTGRES_USER=shelter
        - POSTGRES_PASSWORD=20121208
      ports:
        - "5433:5433"

    cms-shelter:
        image: snslabdocker/cms_shelter
        container_name: cms_shelter
        depends_on:
          - cms-shelter-db
        restart: always
        command: sh -c "/bin/bash /root/LivingLab-ShelterServer/local_shelter_server/start_shelter.sh"
        #command: /bin/bash -c "while true; do echo test; sleep 100; done"
        ports:
          - "8001:8000"